{% set name = "validictory" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a87b84658592f75f37d6bab77ac223774c9989dc7349c8aad19a424770835ba

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - validictory

about:
  home: http://github.com/jamesturk/validictory
  license: MIT
  license_file: LICENSE.txt
  summary: 'A general purpose python data validator'

  description: |
    validictory is a general purpose of Python data validator.
    Works with Python 2.7 and Python 3.3+
  doc_url: http://validictory.readthedocs.io
  dev_url: http://github.com/jamesturk/validictory

extra:
  recipe-maintainers:
    - souravsingh
