travis:
  secure:
    BINSTAR_TOKEN: NIKzSzHnySh/z4a/OzyB9JT4HRTnyJhq56ds7lk1dgxuje7C3vAQFsq5TPxJnv9I0cmQaAJg7L0H4jrZ1tRR/M6fZUCKs744oyKXGQSNJ7qG2lBWi2vV6vhhglUxTGoDPCRyvz124Qz7SYEq4GVMBtPomx0ZoPS/HBcpbRmKJVu2Y9qbdYtQtNjVor8AtY9roSeH8CxTrIAWXkBtxV4A+PkV9XdBTyEhCSwWxJoSElgeQ2KhRd8rIIxmgJHE1YVT0xPinp7d4PhudzarkfK51f5iXz/tGHSVIOujNkvGOHhv9DByrwgYWEIKj1y4+mUu1brKYJdSMV0Lc5L/PMg/elbCB9bKHXZgyfJJ8PEubfnrwRRUAJQar1MsK1diN8jl5jgfQ5VQavhCdG+jHdU9BAy8WNEq94Mt/gl7R33F82FFLejO7iZ4LVTBVC6TSC46EgRtZuNbRk0Uo+hpjsxmnMvUpBRkIOKxfnrr33F42gHuLgbtu5rj3d2nREXkiMXYent33m2iaTrtKR3H5oy0f2gtDFdgcd6JPFfmg8hI1Kn/yEoZq8JSmKjdso/T2zP0TH0NYIZAu/xVkMmi6YIVcnDGc6F12NCEXmGby0VSm/55xBo2dTt9dR4FATlWrzU/APiDIt3/QAj9zTWe9IobrUmNq0c2bB68fdlZMq9HuBI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
