travis:
  secure:
    BINSTAR_TOKEN: a6WW2lie726aCpmQnTeStGvpC2pqBAVE8siMfctwcAITTKehM4Z24wFxtofAfR0OxiGInaE/m+hoNTrknBbOU5DnAN4kBJWoEWevvL2cwzHyWoHZrVJnLJyO3JB3EzkgX0ofzeRB9miFJzSMPX7OLHQhGA0JxpZPJhAyZAelRQhqZB0lHpc/ooIGg+7SDKpWwAGBc+Ciqy2LRWvBDaXrZ1IIR2MUyj7IDdgcsMH7p5dJiO3/mLeAIZXkPc+pu2TPgGds8kUkxwgBnE6sxnrsnhGxcDwIM0AVSa9Pnr2aCRVhQX4Jsi86tNdLQxAP5xhguuRcaBLnSN4K2UDFrF3PtYyltUP7KeHF0sGsPPQc4Q2pF5V6NeQiPDYF0bsGE54EUY19gwDzvSI7aJeK8R92Xr0195msnj6mOVv/RMkr661ryYkf+Z8LI/NQWh/999htSxsyBm/c01KpgUCIHdIOIc5tcG8Gh7bpZYcfaewvzTRosvXwYK4iLB4s5i37aRCNQPKVB1EgdZbzw5ORiiWGztQtu0mTFbgRRezZv4dFjhKAqIjIaksjiYZV33AdnckDrz2mAJuW1wIwdrPGzSmNjCFn6I+BSL9cdIzwDNvUkuheA17LbJEe7ntYWSJmGjWlhg7Phj+J74ir3FrP/EN3YMhU9YZh9gDzqPsku23Tnmk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
